### ISSUE TITLE
Gradle 8.11 API publishing

### ISSUE THREAD

**Issue by rpalcolea** [gradle-plugins/toolbox#114]
Hi @lacasseio 

Hope you are doing great!

Just wanted to check if it would be possible to publish the Gradle API for 8.11 and 8.11.1? 😅 

I'm still hoping for https://github.com/gradle/gradle/issues/29483 to land soon :) 

Thanks in advance and for keeping the Gradle API public for folks! appreciate it!

**Comment by lacasseio** [comment]
Sorry for the delay. Everything has been published they should appear in the repository soon (if it's not already there).
