### ISSUE TITLE
Gradle 8.5 support?

### ISSUE THREAD

**Issue by perlun** [gradle-plugins/toolbox#99]
Hi,

Thanks for an interesting project. I discovered it because it was mentioned here: https://github.com/gradle/gradle/issues/19973#issuecomment-1046727079, which I found because I was also looking into why Logback logging is seemingly "broken" for projects using the Gradle Test Kit in our case.

However, I noticed that https://central.sonatype.com/artifact/dev.gradleplugins/gradle-test-kit/versions doesn't yet contain any Gradle 8.5-targeting version. I guess this just hasn't been done yet, since Gradle 8.5 was released so recently?

**Comment by lacasseio** [comment]
All API JARs for the Gradle distribution should be released. Sorry for the delay between a Gradle release and publish of the JAR. I'm hoping to work on the issue https://github.com/gradle-plugins/toolbox/issues/93 soon, which will avoid being blocked by the delay between the release and publish.

**Comment by rpalcolea** [comment]
hello @lacasseio :) wondering if it would be possible to get a release for 8.11? :)
